name: renovate
on:
  schedule:
    # JST Mon~Fri action on 12:00
    - cron: '0 3 * * 0-4'

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: GitHub Action for npx
        uses: mikeal/npx@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.1.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
